#!/usr/bin/env bash

source /usr/local/etc/colors.sh

function prompt {
    local inversed

    if [[ "$2" == "inverse" ]]; then
        inversed=true
    else
        inversed=false
    fi

    local questionAnswerVariants=$($inversed && echo "[${red}y${clr}|${green}N${clr}]" || echo "[${green}Y${clr}|${red}n${clr}]")
    local ans=""
    while true; do
        echo -n $white""$bright">>> "$clr""$1""$clr" "$questionAnswerVariants" "
        read -n1 ans
        if [[ ! ( $ans =~ [yYnN] || $ans == "" ) ]]; then
            echo ""
            echo "Sorry didn't understand, try again."
        else
            if [[ $ans != "" ]]; then
                echo ""
            fi
            if [[ $ans =~ [yY] || ( $ans == "" && ! "$inversed" == "true" ) ]]; then
                answer=true
            else
                answer=false
            fi
            break
        fi
    done

    local returnCode
    if [[ "$answer" == "true" ]]; then
        returnCode=0
    else
        returnCode=1
    fi
    return $returnCode
}

